-- DropForeignKey
ALTER TABLE "PlayerStats" DROP CONSTRAINT "PlayerStats_Player_fkey";

-- DropIndex
DROP INDEX "PlayerPhotos_player_key";

-- CreateTable
CREATE TABLE "GameStats" (
    "id" SERIAL NOT NULL,
    "PLAYER" TEXT NOT NULL,
    "TEAM" TEXT NOT NULL,
    "MATCH_UP" TEXT,
    "GAME_DATE" TIMESTAMP(3),
    "WL" TEXT,
    "MIN" DOUBLE PRECISION,
    "PTS" DOUBLE PRECISION,
    "FGM" DOUBLE PRECISION,
    "FGA" DOUBLE PRECISION,
    "FG" DOUBLE PRECISION,
    "PM3" DOUBLE PRECISION,
    "PA3" DOUBLE PRECISION,
    "P3" DOUBLE PRECISION,
    "FTM" DOUBLE PRECISION,
    "FTA" DOUBLE PRECISION,
    "FT" DOUBLE PRECISION,
    "OREB" DOUBLE PRECISION,
    "DREB" DOUBLE PRECISION,
    "REB" DOUBLE PRECISION,
    "AST" DOUBLE PRECISION,
    "STL" DOUBLE PRECISION,
    "BLK" DOUBLE PRECISION,
    "TOV" DOUBLE PRECISION,
    "PF" DOUBLE PRECISION,
    "PLUS_MINUS" DOUBLE PRECISION,
    "FP" DOUBLE PRECISION,

    CONSTRAINT "GameStats_pkey" PRIMARY KEY ("id")
);
